/*
 * Jakefile
 * CPDictionaryControllerTest
 *
 * Created by Blair Duncan on February 17, 2013.
 * Copyright 2013, SGL Studio, BBDO Toronto All rights reserved.
 */

var ENV = process.env,
    cp = require("child_process"),
    fs = require("fs"),
    path = require("path"),
    task = JAKE.task,
    FileList = JAKE.FileList,
    app = CAPPUCCINO.Jake.applicationtask.app,
    configuration = ENV["CONFIG"] || ENV["CONFIGURATION"] || ENV["c"] || "Debug";

app ("CPDictionaryControllerTest", function(task)
{
    task.setBuildIntermediatesPath(path.join("Build", "CPDictionaryControllerTest.build", configuration));
    task.setBuildPath(path.join("Build", configuration));

    task.setProductName("CPDictionaryControllerTest");
    task.setIdentifier("com.yourcompany.CPDictionaryControllerTest");
    task.setVersion("1.0");
    task.setAuthor("SGL Studio, BBDO Toronto");
    task.setEmail("Blair.Duncan@BBDO.com");
    task.setSummary("CPDictionaryControllerTest");
    task.setSources((new FileList("**/*.j")).exclude(path.join("Build", "**")));
    task.setResources(new FileList("Resources/**"));
    task.setIndexFilePath("index.html");
    task.setInfoPlistPath("Info.plist");
    task.setNib2CibFlags("-R Resources/");

    if (configuration === "Debug")
        task.setCompilerFlags("-DDEBUG -g");
    else
        task.setCompilerFlags("-O");
});

task ("default", ["CPDictionaryControllerTest"], function()
{
    printResults(configuration);
});

task ("build", ["default"]);

task ("debug", function()
{
    ENV["CONFIGURATION"] = "Debug";
    JAKE.subjake(["."], "build", ENV);
});

task ("release", function()
{
    ENV["CONFIGURATION"] = "Release";
    JAKE.subjake(["."], "build", ENV);
});

task ("run", ["debug"], function()
{
    cp.execSync(["open", path.join("Build", "Debug", "CPDictionaryControllerTest", "index.html")].join(" "), { stdio: "inherit" });
});

task ("run-release", ["release"], function()
{
    cp.execSync(["open", path.join("Build", "Release", "CPDictionaryControllerTest", "index.html")].join(" "), { stdio: "inherit" });
});

task ("deploy", ["release"], function()
{
    fs.mkdirSync(path.join("Build", "Deployment", "CPDictionaryControllerTest"), { recursive: true });
    cp.execSync(["press", "-f", path.join("Build", "Release", "CPDictionaryControllerTest"), path.join("Build", "Deployment", "CPDictionaryControllerTest")].join(" "), { stdio: "inherit" });
    printResults("Deployment")
});

task ("desktop", ["release"], function()
{
    fs.mkdirSync(path.join("Build", "Desktop", "CPDictionaryControllerTest"), { recursive: true });
    require("@objj/nativehost").buildNativeHost(path.join("Build", "Release", "CPDictionaryControllerTest"), path.join("Build", "Desktop", "CPDictionaryControllerTest", "CPDictionaryControllerTest.app"));
    printResults("Desktop")
});

task ("run-desktop", ["desktop"], function()
{
    cp.execSync([path.join("Build", "Desktop", "CPDictionaryControllerTest", "CPDictionaryControllerTest.app", "Contents", "MacOS", "NativeHost"), "-i"].join(" "), { stdio: "inherit" });
});

function printResults(configuration)
{
    console.log("----------------------------");
    console.log(configuration+" app built at path: "+path.join("Build", configuration, "CPDictionaryControllerTest"));
    console.log("----------------------------");
}
