console.log("at the top of CommonJS/Jakefile");

require("../common.jake");

const { FileList } = require("../common.jake");
const { task } = require("../common.jake");
const { filedir } = require("../common.jake");

// var FILE = require("file");
var fs = require("fs");
var path = require("path");

var tmp_list = new FileList();
tmp_list.include("**/*");
tmp_list.exclude("Jakefile");

tmp_list.forEach(function(aFilename)
{
    
    if (!fs.lstatSync(aFilename).isFile())
        return;

    var buildFilename = path.join($BUILD_CJS_CAPPUCCINO, aFilename);

    filedir (buildFilename, [aFilename], function ()
    {
        cp(aFilename, buildFilename);
    });

    // HACK: narwhal should copy permissions
    if (path.dirname(aFilename) === path.join("bin"))
    {
        filedir (buildFilename, function ()
        {
            fs.chmodSync(buildFilename, 0o755);
        });
    }

    task ("build", buildFilename);
    CLOBBER.include(buildFilename);
});

task ("build", function() {
    setPackageMetadata(path.join($BUILD_CJS_CAPPUCCINO, "package.json"));
});
