
require("../common.jake");

var FILE = require("file");

new FileList("**/*").exclude("Jakefile").forEach(function(aFilename)
{
    if (!FILE.isFile(aFilename))
        return;

    var buildFilename = FILE.join($BUILD_CJS_CAPPUCCINO, aFilename);

    filedir (buildFilename, [aFilename], function ()
    {
        cp(aFilename, buildFilename);
    });

    // HACK: narwhal should copy permissions
    if (FILE.dirname(aFilename) === FILE.join("bin"))
    {
        filedir (buildFilename, function ()
        {
            FILE.chmod(buildFilename, 0755);
        });
    }

    task ("build", buildFilename);
    CLOBBER.include(buildFilename);
});

task ("build", function() {
    setPackageMetadata(FILE.join($BUILD_CJS_CAPPUCCINO, "package.json"));
});
