/*
 * Jakefile
 * CPTabView2Test
 *
 * Created by You on August 27, 2010.
 * Copyright 2010, Your Company All rights reserved.
 */

var ENV = process.env,
    cp = require("child_process"),
    fs = require("fs"),
    path = require("path"),
    task = JAKE.task,
    FileList = JAKE.FileList,
    app = CAPPUCCINO.Jake.applicationtask.app,
    configuration = ENV["CONFIG"] || ENV["CONFIGURATION"] || ENV["c"] || "Debug";

app ("CPTabView2Test", function(task)
{
    task.setBuildIntermediatesPath(path.join("Build", "CPTabView2Test.build", configuration));
    task.setBuildPath(path.join("Build", configuration));

    task.setProductName("CPTabView2Test");
    task.setIdentifier("com.yourcompany.CPTabView2Test");
    task.setVersion("1.0");
    task.setAuthor("Your Company");
    task.setEmail("feedback @nospam@ yourcompany.com");
    task.setSummary("CPTabView2Test");
    task.setSources((new FileList("**/*.j")).exclude(path.join("Build", "**")));
    task.setResources(new FileList("Resources/**"));
    task.setIndexFilePath("index.html");
    task.setInfoPlistPath("Info.plist");

    if (configuration === "Debug")
        task.setCompilerFlags("-DDEBUG -g");
    else
        task.setCompilerFlags("-O");
});

task ("default", ["CPTabView2Test"], function()
{
    printResults(configuration);
});

task ("build", ["default"]);

task ("debug", function()
{
    ENV["CONFIGURATION"] = "Debug";
    JAKE.subjake(["."], "build", ENV);
});

task ("release", function()
{
    ENV["CONFIGURATION"] = "Release";
    JAKE.subjake(["."], "build", ENV);
});

task ("run", ["debug"], function()
{
    cp.execSync(["open", path.join("Build", "Debug", "CPTabView2Test", "index.html")].join(" "), { stdio: "inherit" });
});

task ("run-release", ["release"], function()
{
    cp.execSync(["open", path.join("Build", "Release", "CPTabView2Test", "index.html")].join(" "), { stdio: "inherit" });
});

task ("deploy", ["release"], function()
{
    fs.mkdirSync(path.join("Build", "Deployment", "CPTabView2Test"), { recursive: true });
    cp.execSync(["press", "-f", path.join("Build", "Release", "CPTabView2Test"), path.join("Build", "Deployment", "CPTabView2Test")].join(" "), { stdio: "inherit" });
    printResults("Deployment")
});

task ("desktop", ["release"], function()
{
    fs.mkdirSync(path.join("Build", "Desktop", "CPTabView2Test"), { recursive: true });
    require("@objj/nativehost").buildNativeHost(path.join("Build", "Release", "CPTabView2Test"), path.join("Build", "Desktop", "CPTabView2Test", "CPTabView2Test.app"));
    printResults("Desktop")
});

task ("run-desktop", ["desktop"], function()
{
    cp.execSync([path.join("Build", "Desktop", "CPTabView2Test", "CPTabView2Test.app", "Contents", "MacOS", "NativeHost"), "-i"].join(" "), { stdio: "inherit" });
});

function printResults(configuration)
{
    console.log("----------------------------");
    console.log(configuration+" app built at path: "+path.join("Build", configuration, "CPTabView2Test"));
    console.log("----------------------------");
}
