/*
 * Jakefile
 * CPTextFieldContentInset
 *
 * Created by aparajita on May 9, 2011.
 * Copyright 2011, Victory-Heart Productions All rights reserved.
 */

var ENV = require("system").env,
    FILE = require("file"),
    JAKE = require("jake"),
    task = JAKE.task,
    FileList = JAKE.FileList,
    app = require("cappuccino/jake").app,
    configuration = ENV["CONFIG"] || ENV["CONFIGURATION"] || ENV["c"] || "Debug",
    OS = require("os");

app ("CPTextFieldContentInset", function(task)
{
    task.setBuildIntermediatesPath(FILE.join("Build", "CPTextFieldContentInset.build", configuration));
    task.setBuildPath(FILE.join("Build", configuration));

    task.setProductName("CPTextFieldContentInset");
    task.setIdentifier("com.aparajita.CPTextFieldContentInset");
    task.setVersion("1.0");
    task.setAuthor("Victory-Heart Productions");
    task.setEmail("feedback @nospam@ yourcompany.com");
    task.setSummary("CPTextFieldContentInset");
    task.setSources((new FileList("**/*.j")).exclude(FILE.join("Build", "**")));
    task.setResources(new FileList("Resources/**"));
    task.setIndexFilePath("index.html");
    task.setInfoPlistPath("Info.plist");

    if (configuration === "Debug")
        task.setCompilerFlags("-DDEBUG -g");
    else
        task.setCompilerFlags("-O");
});

task ("default", ["CPTextFieldContentInset"], function()
{
    printResults(configuration);
});

task ("build", ["default"]);

task ("debug", function()
{
    ENV["CONFIGURATION"] = "Debug";
    JAKE.subjake(["."], "build", ENV);
});

task ("release", function()
{
    ENV["CONFIGURATION"] = "Release";
    JAKE.subjake(["."], "build", ENV);
});

task ("run", ["debug"], function()
{
    OS.system(["open", FILE.join("Build", "Debug", "CPTextFieldContentInset", "index.html")]);
});

task ("run-release", ["release"], function()
{
    OS.system(["open", FILE.join("Build", "Release", "CPTextFieldContentInset", "index.html")]);
});

task ("deploy", ["release"], function()
{
    FILE.mkdirs(FILE.join("Build", "Deployment", "CPTextFieldContentInset"));
    OS.system(["press", "-f", FILE.join("Build", "Release", "CPTextFieldContentInset"), FILE.join("Build", "Deployment", "CPTextFieldContentInset")]);
    printResults("Deployment")
});

task ("desktop", ["release"], function()
{
    FILE.mkdirs(FILE.join("Build", "Desktop", "CPTextFieldContentInset"));
    require("cappuccino/nativehost").buildNativeHost(FILE.join("Build", "Release", "CPTextFieldContentInset"), FILE.join("Build", "Desktop", "CPTextFieldContentInset", "CPTextFieldContentInset.app"));
    printResults("Desktop")
});

task ("run-desktop", ["desktop"], function()
{
    OS.system([FILE.join("Build", "Desktop", "CPTextFieldContentInset", "CPTextFieldContentInset.app", "Contents", "MacOS", "NativeHost"), "-i"]);
});

function printResults(configuration)
{
    print("----------------------------");
    print(configuration+" app built at path: "+FILE.join("Build", configuration, "CPTextFieldContentInset"));
    print("----------------------------");
}
