#!/usr/bin/env ruby

require 'rake'
require '../../../common'
require 'objective-j'


$BUNDLE_SCRIPT          = File.join($BUILD_DIR, 'bundle.build', $CONFIGURATION, 'main-concat.js')
$BUNDLE_CLASS           = File.join($ENVIRONMENT_LIB_DIR, 'bundle', 'main.class')
$BUNDLE_EXECUTABLE      = File.join($ENVIRONMENT_BIN_DIR, 'bundle')
$STANDARD_EXECUTABLE    = File.expand_path(File.join('..', 'executable'))

task :build => [$BUNDLE_CLASS, $BUNDLE_EXECUTABLE]

Files = [   File.join($HOME_DIR, 'Tools', 'Utilities', 'bridge.js'), #yuck!
            File.join($ENVIRONMENT_FRAMEWORKS_DIR, 'Objective-J', 'Rhino.platform', 'Objective-J.js'),
            'main.js'];

file_d $BUNDLE_EXECUTABLE => [$STANDARD_EXECUTABLE] do
    cp($STANDARD_EXECUTABLE, $BUNDLE_EXECUTABLE)
    File.chmod 0755, $BUNDLE_EXECUTABLE
end

file_d $BUNDLE_SCRIPT => Files do |t|
    cat(Files, $BUNDLE_SCRIPT)
end

file_d $BUNDLE_CLASS => $BUNDLE_SCRIPT do |t|
    js2java($BUNDLE_SCRIPT, 'main.class', false)
    cp(File.join(File.dirname($BUNDLE_SCRIPT), 'main.class'), $BUNDLE_CLASS)
end
