/*
 * Jakefile
 * ScalingTest
 *
 * Created by You on July 23, 2013.
 * Copyright 2013, Your Company All rights reserved.
 */

var ENV = process.env,
    cp = require("child_process"),
    fs = require("fs"),
    path = require("path"),
    task = JAKE.task,
    FileList = JAKE.FileList,
    app = CAPPUCCINO.Jake.applicationtask.app,
    configuration = ENV["CONFIG"] || ENV["CONFIGURATION"] || ENV["c"] || "Debug";

app ("ScalingTest", function(task)
{
    ENV["OBJJ_INCLUDE_PATHS"] = "Frameworks";

    if (configuration === "Debug")
        ENV["OBJJ_INCLUDE_PATHS"] = path.join(ENV["OBJJ_INCLUDE_PATHS"], configuration);

    task.setBuildIntermediatesPath(path.join("Build", "ScalingTest.build", configuration));
    task.setBuildPath(path.join("Build", configuration));

    task.setProductName("ScalingTest");
    task.setIdentifier("com.yourcompany.ScalingTest");
    task.setVersion("1.0");
    task.setAuthor("Your Company");
    task.setEmail("feedback @nospam@ yourcompany.com");
    task.setSummary("ScalingTest");
    task.setSources(new FileList("**/*.j").exclude(path.join("Build", "**")).exclude(path.join("Frameworks", "Source", "**")));
    task.setResources(new FileList("Resources/**"));
    task.setIndexFilePath("index.html");
    task.setInfoPlistPath("Info.plist");

    if (configuration === "Debug")
        task.setCompilerFlags("-DDEBUG -g");
    else
        task.setCompilerFlags("-O");
});

task ("default", ["ScalingTest"], function()
{
    printResults(configuration);
});

task ("build", ["default"]);

task ("debug", function()
{
    ENV["CONFIGURATION"] = "Debug";
    JAKE.subjake(["."], "build", ENV);
});

task ("release", function()
{
    ENV["CONFIGURATION"] = "Release";
    JAKE.subjake(["."], "build", ENV);
});

task ("run", ["debug"], function()
{
    cp.execSync(["open", path.join("Build", "Debug", "ScalingTest", "index.html")].join(" "), { stdio: "inherit" });
});

task ("run-release", ["release"], function()
{
    cp.execSync(["open", path.join("Build", "Release", "ScalingTest", "index.html")].join(" "), { stdio: "inherit" });
});

task ("deploy", ["release"], function()
{
    fs.mkdirSync(path.join("Build", "Deployment", "ScalingTest"), { recursive: true });
    cp.execSync(["press", "-f", path.join("Build", "Release", "ScalingTest"), path.join("Build", "Deployment", "ScalingTest")].join(" "), { stdio: "inherit" });
    printResults("Deployment")
});

task ("desktop", ["release"], function()
{
    fs.mkdirSync(path.join("Build", "Desktop", "ScalingTest"), { recursive: true });
    require("@objj/nativehost").buildNativeHost(path.join("Build", "Release", "ScalingTest"), path.join("Build", "Desktop", "ScalingTest", "ScalingTest.app"));
    printResults("Desktop")
});

task ("run-desktop", ["desktop"], function()
{
    cp.execSync([path.join("Build", "Desktop", "ScalingTest", "ScalingTest.app", "Contents", "MacOS", "NativeHost"), "-i"].join(" "), { stdio: "inherit" });
});

function printResults(configuration)
{
    console.log("----------------------------");
    console.log(configuration+" app built at path: "+path.join("Build", configuration, "ScalingTest"));
    console.log("----------------------------");
}
