/*
 * Jakefile
 * CPToolbarTest
 *
 * Created by Alexander Ljungberg on June 12, 2012.
 * Copyright 2012, SlevenBits Ltd. All rights reserved.
 */

var ENV = process.env,
    cp = require("child_process"),
    fs = require("fs"),
    path = require("path"),
    task = JAKE.task,
    FileList = JAKE.FileList,
    app = CAPPUCCINO.Jake.applicationtask.app,
    configuration = ENV["CONFIG"] || ENV["CONFIGURATION"] || ENV["c"] || "Debug";

app ("CPToolbarTest", function(task)
{
    task.setBuildIntermediatesPath(path.join("Build", "CPToolbarTest.build", configuration));
    task.setBuildPath(path.join("Build", configuration));

    task.setProductName("CPToolbarTest");
    task.setIdentifier("com.slevenbits.CPToolbarTest");
    task.setVersion("1.0");
    task.setAuthor("Your Company");
    task.setEmail("feedback @nospam@ yourcompany.com");
    task.setSummary("CPToolbarTest");
    task.setSources((new FileList("**/*.j")).exclude(path.join("Build", "**")));
    task.setResources(new FileList("Resources/**"));
    task.setIndexFilePath("index.html");
    task.setInfoPlistPath("Info.plist");

    if (configuration === "Debug")
        task.setCompilerFlags("-DDEBUG -g");
    else
        task.setCompilerFlags("-O");
});

task ("default", ["CPToolbarTest"], function()
{
    printResults(configuration);
});

task ("build", ["default"]);

task ("debug", function()
{
    ENV["CONFIGURATION"] = "Debug";
    JAKE.subjake(["."], "build", ENV);
});

task ("release", function()
{
    ENV["CONFIGURATION"] = "Release";
    JAKE.subjake(["."], "build", ENV);
});

task ("run", ["debug"], function()
{
    cp.execSync(["open", path.join("Build", "Debug", "CPToolbarTest", "index.html")].join(" "), { stdio: "inherit" });
});

task ("run-release", ["release"], function()
{
    cp.execSync(["open", path.join("Build", "Release", "CPToolbarTest", "index.html")].join(" "), { stdio: "inherit" });
});

task ("deploy", ["release"], function()
{
    fs.mkdirSync(path.join("Build", "Deployment", "CPToolbarTest"), { recursive: true });
    cp.execSync(["press", "-f", path.join("Build", "Release", "CPToolbarTest"), path.join("Build", "Deployment", "CPToolbarTest")].join(" "), { stdio: "inherit" });
    printResults("Deployment")
});

task ("desktop", ["release"], function()
{
    fs.mkdirSync(path.join("Build", "Desktop", "CPToolbarTest"), { recursive: true });
    require("@objj/nativehost").buildNativeHost(path.join("Build", "Release", "CPToolbarTest"), path.join("Build", "Desktop", "CPToolbarTest", "CPToolbarTest.app"));
    printResults("Desktop")
});

task ("run-desktop", ["desktop"], function()
{
    cp.execSync([path.join("Build", "Desktop", "CPToolbarTest", "CPToolbarTest.app", "Contents", "MacOS", "NativeHost"), "-i"].join(" "), { stdio: "inherit" });
});

function printResults(configuration)
{
    console.log("----------------------------");
    console.log(configuration+" app built at path: "+path.join("Build", configuration, "CPToolbarTest"));
    console.log("----------------------------");
}
