
require("../common.jake");

var framework = require("../Jake/frameworktask.js").framework,
    BundleTask = require("../Jake/bundletask.js").BundleTask;

const path = require("path");

$BUILD_PATH = path.join($BUILD_DIR, $CONFIGURATION, 'AppKit');

AppKitFiles = new FileList("**/*.j").exclude('CoreGraphics/CGContextCanvas.j', 'CoreGraphics/CGContextVML.j', 'Themes/**/*', 'Tools/**/*', "Platform/DOM/CPPlatform.j", "Platform/DOM/CPPlatformString.j");

FIXME_fileDependency (path.join("Platform", "CPPlatform.j"), path.join("Platform", "DOM", "CPPlatform.j"));
FIXME_fileDependency (path.join("Platform", "CPPlatformString.j"), path.join("Platform", "DOM", "CPPlatformString.j"));

appKitTask = framework ("AppKit", function(appKitTask)
{
    appKitTask.setBuildIntermediatesPath(path.join($BUILD_DIR, "AppKit.build", $CONFIGURATION))
    appKitTask.setBuildPath($BUILD_CONFIGURATION_DIR);

    appKitTask.setAuthor("280 North, Inc.");
    appKitTask.setEmail("feedback @nospam@ 280north.com");
    appKitTask.setSummary("AppKit classes for Cappuccino");
    appKitTask.setIdentifier("com.280n.AppKit");
    appKitTask.setVersion(getCappuccinoVersion());
    appKitTask.setLicense(BundleTask.License.LGPL_v2_1);
    appKitTask.setSources(AppKitFiles);
    appKitTask.setResources(new FileList("Resources/**/*"));
    appKitTask.setFlattensSources(true);
    appKitTask.setInfoPlistPath("Info.plist");

    // Grab all the .h's and just include them in each file.
    var INCLUDES = new FileList("**/*.h").map(function(aFilename)
    {
        return "--include \"" + aFilename + "\"";
    }).join(" ");

    if ($CONFIGURATION === "Release") {
        appKitTask.setCompilerFlags("-O2 -Wno-unused-but-set-variable " + INCLUDES);
    }
    else
        appKitTask.setCompilerFlags("-DDEBUG -g -S --inline-msg-send -Wno-unused-but-set-variable " + INCLUDES);
});

$BUILD_CJS_CAPPUCCINO_APPKIT = path.join($BUILD_CJS_CAPPUCCINO_FRAMEWORKS, "AppKit");

filedir ($BUILD_CJS_CAPPUCCINO_APPKIT, ["AppKit"], function()
{
    cp_r(appKitTask.buildProductPath(), $BUILD_CJS_CAPPUCCINO_APPKIT);
});

subtasks (["Themes"], ["clean", "clobber"]);

task ("Theme", [$BUILD_CJS_CAPPUCCINO_APPKIT], function()
{
    console.log("in task Theme in appkit");
    subjake(["Themes"], "build");

    cp_r(path.join($BUILD_DIR, $CONFIGURATION, 'Aristo.blend'), path.join($BUILD_PATH, 'Resources', 'Aristo.blend'));
    cp_r(path.join($BUILD_DIR, $CONFIGURATION, 'Aristo.blend'), path.join($BUILD_CJS_CAPPUCCINO_APPKIT, "Resources", "Aristo.blend"));

    cp_r(path.join($BUILD_DIR, $CONFIGURATION, 'Aristo2.blend'), path.join($BUILD_PATH, 'Resources', 'Aristo2.blend'));
    cp_r(path.join($BUILD_DIR, $CONFIGURATION, 'Aristo2.blend'), path.join($BUILD_CJS_CAPPUCCINO_APPKIT, "Resources", "Aristo2.blend"));
});

task ("build", ["AppKit", $BUILD_CJS_CAPPUCCINO_APPKIT, "Theme"]);

CLOBBER.include($BUILD_CJS_CAPPUCCINO_APPKIT);
