#!/usr/bin/env ruby

require 'rake'
require '../../../common'
require 'objective-j'
require 'objective-j/bundletask'


$ENVIRONMENT_PRODUCT = File.join($ENVIRONMENT_FRAMEWORKS_DIR, 'BlendKit')
$BUILD_PATH = File.join($BUILD_DIR, $CONFIGURATION, 'BlendKit')

ObjectiveJ::BundleTask.new(:BlendKit) do |t|
    t.name          = 'BlendKit'
    t.identifier    = 'com.280n.BlendKit'
    t.version       = '0.6.5'
    t.author        = '280 North, Inc.'
    t.email         = 'feedback @nospam@ 280north.com'
    t.summary       = 'BlendKit classes for Cappuccino'
    t.sources       = FileList['*.j']
    t.resources     = FileList['Resources/*'].to_a
    t.license       = ObjectiveJ::License::LGPL_v2_1
    t.build_path    = $BUILD_PATH
    t.flag          = 'DEBUG' if $CONFIGURATION == 'Debug'
end

#Framework in environment directory
file_d $ENVIRONMENT_PRODUCT => [:BlendKit] do
    cp_r(File.join($BUILD_PATH, '.'), $ENVIRONMENT_PRODUCT)
end

task :build => [:BlendKit, $ENVIRONMENT_PRODUCT]

CLOBBER.include($ENVIRONMENT_PRODUCT)
