/*
 * Jakefile
 * CPLanguageModelChatbotTest
 *
 * Created by Alexander Ljungberg on May 28, 2011.
 * Copyright 2011, WireLoad All rights reserved.
 */

var ENV = process.env,
    cp = require("child_process"),
    fs = require("fs"),
    path = require("path"),
    task = JAKE.task,
    FileList = JAKE.FileList,
    app = CAPPUCCINO.Jake.applicationtask.app,
    configuration = ENV["CONFIG"] || ENV["CONFIGURATION"] || ENV["c"] || "Debug";

app ("CPLanguageModelChatbotTest", function(task)
{
    task.setBuildIntermediatesPath(path.join("Build", "CPLanguageModelChatbotTest.build", configuration));
    task.setBuildPath(path.join("Build", configuration));

    task.setProductName("CPLanguageModelChatbotTest");
    task.setIdentifier("com.yourcompany.CPLanguageModelChatbotTest");
    task.setVersion("1.0");
    task.setAuthor("WireLoad");
    task.setEmail("feedback @nospam@ yourcompany.com");
    task.setSummary("CPLanguageModelChatbotTest");
    task.setSources((new FileList("**/*.j")).exclude(path.join("Build", "**")));
    task.setResources(new FileList("Resources/**"));
    task.setIndexFilePath("index.html");
    task.setInfoPlistPath("Info.plist");
    task.setNib2CibFlags("-R Resources/");

    if (configuration === "Debug")
        task.setCompilerFlags("-DDEBUG -g");
    else
        task.setCompilerFlags("-O");
});

task ("default", ["CPLanguageModelChatbotTest"], function()
{
    printResults(configuration);
});

task ("build", ["default"]);

task ("debug", function()
{
    ENV["CONFIGURATION"] = "Debug";
    JAKE.subjake(["."], "build", ENV);
});

task ("release", function()
{
    ENV["CONFIGURATION"] = "Release";
    JAKE.subjake(["."], "build", ENV);
});

task ("run", ["debug"], function()
{
    cp.execSync(["open", path.join("Build", "Debug", "CPLanguageModelChatbotTest", "index.html")].join(" "), { stdio: "inherit" });
});

task ("run-release", ["release"], function()
{
    cp.execSync(["open", path.join("Build", "Release", "CPLanguageModelChatbotTest", "index.html")].join(" "), { stdio: "inherit" });
});

task ("deploy", ["release"], function()
{
    fs.mkdirSync(path.join("Build", "Deployment", "CPLanguageModelChatbotTest"), { recursive: true });
    cp.execSync(["press", "-f", path.join("Build", "Release", "CPLanguageModelChatbotTest"), path.join("Build", "Deployment", "CPLanguageModelChatbotTest")].join(" "), { stdio: "inherit" });
    printResults("Deployment")
});

task ("desktop", ["release"], function()
{
    fs.mkdirSync(path.join("Build", "Desktop", "CPLanguageModelChatbotTest"), { recursive: true });
    require("@objj/nativehost").buildNativeHost(path.join("Build", "Release", "CPLanguageModelChatbotTest"), path.join("Build", "Desktop", "CPLanguageModelChatbotTest", "CPLanguageModelChatbotTest.app"));
    printResults("Desktop")
});

task ("run-desktop", ["desktop"], function()
{
    cp.execSync([path.join("Build", "Desktop", "CPLanguageModelChatbotTest", "CPLanguageModelChatbotTest.app", "Contents", "MacOS", "NativeHost"), "-i"].join(" "), { stdio: "inherit" });
});

function printResults(configuration)
{
    console.log("----------------------------");
    console.log(configuration+" app built at path: "+path.join("Build", configuration, "CPLanguageModelChatbotTest"));
    console.log("----------------------------");
}
