#!/usr/bin/env narwhal


var FILE = require("file");

require(FILE.absolute("../common.jake"));

$BUILD_PATH = FILE.join($BUILD_DIR, $CONFIGURATION, "Foundation");

task ("build", ["Foundation"]);

framework ("Foundation", function(foundationTask)
{
    foundationTask.setBuildIntermediatesPath(FILE.join($BUILD_DIR, "Foundation.build", $CONFIGURATION))
    foundationTask.setBuildPath(FILE.join($BUILD_DIR, $CONFIGURATION));
    
    foundationTask.setIdentifier("com.280n.Foundation");
    foundationTask.setLicense(BundleTask.License.LGPL_v2_1);
    foundationTask.setSources(FILE.glob("**/*.j").concat(FILE.glob("*.j")));//terrible!
    foundationTask.setResources(FILE.glob("Resources/*"));
});

//CLOBBER.include($ENVIRONMENT_PRODUCT)
