#!/usr/bin/env narwhal

require("../common.jake");


foundationTask = framework ("Foundation", function(foundationTask)
{
    foundationTask.setBuildIntermediatesPath(FILE.join($BUILD_DIR, "Foundation.build", $CONFIGURATION))
    foundationTask.setBuildPath(FILE.join($BUILD_DIR, $CONFIGURATION));

    foundationTask.setAuthor("280 North, Inc.");
    foundationTask.setEmail("feedback @nospam@ 280north.com");
    foundationTask.setSummary("Foundation classes for Cappuccino");
    foundationTask.setIdentifier("com.280n.Foundation");
    foundationTask.setLicense(BundleTask.License.LGPL_v2_1);
    foundationTask.setSources(FILE.glob("**/*.j").concat(FILE.glob("*.j")));//terrible!
    foundationTask.setResources(FILE.glob("Resources/*"));
    foundationTask.setFlattensSources(true);

    if ($CONFIGURATION === "Release")
        foundationTask.setCompilerFlags("-O");
    else
        foundationTask.setCompilerFlags("-DDEBUG -g");
});

$COMMONJS_PRODUCT_FOUNDATION = FILE.join($COMMONJS_PRODUCT_FRAMEWORKS, "Foundation");

filedir ($COMMONJS_PRODUCT_FOUNDATION, ["Foundation"], function()
{
    cp_r(foundationTask.buildProductPath(), $COMMONJS_PRODUCT_FOUNDATION);
});

task ("build", ["Foundation", $COMMONJS_PRODUCT_FOUNDATION]);

//CLOBBER.include($ENVIRONMENT_PRODUCT)
