#!/usr/bin/env ruby

require 'rake'
require '../common'
require 'objective-j'
require 'objective-j/bundletask'


$ENVIRONMENT_PRODUCT = File.join($ENVIRONMENT_FRAMEWORKS_DIR, 'Foundation')
$BUILD_PATH = File.join($BUILD_DIR, $CONFIGURATION, 'Foundation')

task :build => [:Foundation, $ENVIRONMENT_PRODUCT]

ObjectiveJ::BundleTask.new(:Foundation) do |t|
    t.name          = 'Foundation'
    t.identifier    = 'com.280n.Foundation'
    t.version       = '0.6.5'
    t.author        = '280 North, Inc.'
    t.email         = 'feedback @nospam@ 280north.com'
    t.summary       = 'Foundation classes for Cappuccino'
    t.sources       = FileList['*.j']
    t.resources     = FileList['Resources/*'].to_a
    t.license       = ObjectiveJ::License::LGPL_v2_1
    t.build_path    = $BUILD_PATH
    t.flag          = 'DEBUG' if $CONFIGURATION == 'Debug'
    t.type          = ObjectiveJ::Bundle::Type::Framework
end

#Framework in environment directory
file_d $ENVIRONMENT_PRODUCT => [:Foundation] do
    cp_r(File.join($BUILD_PATH, '.'), $ENVIRONMENT_PRODUCT)
end

CLOBBER.include($ENVIRONMENT_PRODUCT)
