
require("../../common.jake");

// var FILE = require("file");

const path = require("path");
const glob = require("glob");

var app = require("../../Jake/applicationtask.js").app;
var BundleTask = require("../../Jake/bundletask.js").BundleTask;

app ("nib2cib", function(nib2cibTask)
{
    nib2cibTask.setBuildIntermediatesPath(path.join($BUILD_DIR, "nib2cib.build", $CONFIGURATION))
    nib2cibTask.setBuildPath($BUILD_CJS_CAPPUCCINO_LIB);

    nib2cibTask.setIdentifier("com.280n.nib2cib");
    nib2cibTask.setLicense(BundleTask.License.LGPL_v2_1);
    nib2cibTask.setVersion(getCappuccinoVersion());
    nib2cibTask.setAuthor("280 North, Inc.");
    nib2cibTask.setEmail("feedback @nospam@ 280north.com");
    nib2cibTask.setSummary("nib2cib converts Cocoa nib and xibs to Cappuccino cibs");
    
    nib2cibTask.setSources(glob.sync("**/*.j"));
    nib2cibTask.setResources(glob.sync("Resources/*"));
    nib2cibTask.setEnvironments(require("../../Jake/environment.js").CommonJS);
    nib2cibTask.setFlattensSources(true);

    if ($CONFIGURATION === "Release")
        nib2cibTask.setCompilerFlags("-O2 -Wno-unused-but-set-variable ");
    else
        nib2cibTask.setCompilerFlags("-DDEBUG -g  -Wno-unused-but-set-variable ");
});

$BUILD_CJS_NIB2CIB = path.join($BUILD_CJS_CAPPUCCINO_BIN, 'nib2cib');

// executable in environment directory
filedir($BUILD_CJS_NIB2CIB, ["nib2cib"], function()
{
    make_objj_executable($BUILD_CJS_NIB2CIB);
});

copyManPage("nib2cib", 1);

task ("build", ["nib2cib", $BUILD_CJS_NIB2CIB]);

CLOBBER.include($BUILD_CJS_NIB2CIB);
