#!/usr/bin/env ruby

require 'rake'
require '../../common'
require 'objective-j'
require 'objective-j/bundletask'


$PRODUCT = :nib2cib
$BUILD_PATH = File.join($BUILD_DIR, $CONFIGURATION, 'nib2cib')
$ENVIRONMENT_BIN_PRODUCT = File.join($ENVIRONMENT_BIN_DIR, 'nib2cib')
$ENVIRONMENT_LIB_PRODUCT = File.join($ENVIRONMENT_LIB_DIR, 'nib2cib')

ObjectiveJ::BundleTask.new(:nib2cib) do |t|
    t.name          = 'nib2cib'
    t.identifier    = 'com.280n.nib2cib'
    t.version       = '0.6.5'
    t.author        = '280 North, Inc.'
    t.email         = 'feedback @nospam@ 280north.com'
    t.summary       = 'nib2cib converts Cocoa nib and xibs to Cappuccino cibs'
    t.sources       = FileList['**/*.j']
    t.resources     = FileList['Resources/*']
    t.license       = ObjectiveJ::License::LGPL_v2_1
    t.build_path    = $BUILD_PATH
    t.flag          = '-DDEBUG' if $CONFIGURATION == 'Debug'
    t.flag          = '-O' if $CONFIGURATION == 'Release'
end

#executable in environment directory
file_d $ENVIRONMENT_BIN_PRODUCT do
    make_objj_executable($ENVIRONMENT_BIN_PRODUCT)
end

file_d $ENVIRONMENT_LIB_PRODUCT => [:nib2cib] do
    cp_r(File.join($BUILD_PATH, '.'), $ENVIRONMENT_LIB_PRODUCT)
end

task :build => [:nib2cib, $ENVIRONMENT_BIN_PRODUCT, $ENVIRONMENT_LIB_PRODUCT]

CLOBBER.include($ENVIRONMENT_BIN_PRODUCT, $ENVIRONMENT_LIB_PRODUCT )
