.Dd May 5, 2011
.Os "Cappuccino"
.Dt DUMP_THEME 1 "PRM"
.\"-----------------------------------------------------------------------------------------
.Sh NAME
.\"-----------------------------------------------------------------------------------------
.Nm dump_theme
.Nd formatted dump of a Cappuccino theme
.\"-----------------------------------------------------------------------------------------
.Sh SYNOPSIS
.\"-----------------------------------------------------------------------------------------
.Nm
.Op --no-color
.Op Ar name | blend-path
.\"-----------------------------------------------------------------------------------------
.Sh "DESCRIPTION"
.\"-----------------------------------------------------------------------------------------
.Nm
prints a formatted dump of the contents of a Cappuccino theme.
.Pp
If you don't pass any arguments,
.Nm
will attempt to find the default AppKit theme from AppKit's Info.plist. If that cannot be
found, "Aristo2" is used.
.Pp
If you pass a theme name only (without a ".blend" suffix),
.Nm
will attempt to locate the named theme blend in your $CAPP_BUILD and install frameworks.
.Pp
If you pass a theme blend path (thats end with ".blend"),
.Nm
will dump the theme at that location.
.\"-----------------------------------------------------------------------------------------
.Sh "OPTIONS"
.\"-----------------------------------------------------------------------------------------
The following options are available:
.Bl -tag -width 4n
.It Fl \-no-color
Normally
.Nm
uses in addition to indentation to make it easier to read the output. You can turn
colorizing off by passing this option.
.El
.\"-----------------------------------------------------------------------------------------
.Sh "RETURN VALUES"
.\"-----------------------------------------------------------------------------------------
.Nm
returns 0 for a successful conversion and >0 if an error occurred.
