
require ("../../common.jake");

var FILE = require("file"),
    SYSTEM = require("system"),
    path = FILE.Path(FILE.join(SYSTEM.prefix, "bin", "dump_theme"));

sudo(["cp", "-f", "dump_theme", path]);
sudo(["chmod", "755", path]);
copyManPage("dump_theme", 1);
