
require ("../../common.jake");

var FILE = require("file"),
    SYSTEM = require("system"),
    path = FILE.Path(FILE.join(SYSTEM.prefix, "bin", "dump_theme"));

FILE.copy("dump_theme", path);
path.chmod(0755);

copyManPage("dump_theme", 1);
