
require("../../../common.jake");

const path = require("path");

var framework = require("../../../Jake/frameworktask.js").framework;
var BundleTask = require("../../../Jake/bundletask.js").BundleTask;

blendKitTask = framework ("BlendKit", function(blendKitTask)
{
    blendKitTask.setBuildIntermediatesPath(path.join($BUILD_DIR, "BlendKit.build", $CONFIGURATION))
    blendKitTask.setBuildPath(path.join($BUILD_DIR, $CONFIGURATION));

    blendKitTask.setIdentifier("com.280n.BlendKit");
    blendKitTask.setVersion(getCappuccinoVersion());
    blendKitTask.setAuthor("280 North, Inc.");
    blendKitTask.setEmail("feedback @nospam@ 280north.com");
    blendKitTask.setSummary("BlendKit classes for Cappuccino");
    blendKitTask.setSources(new FileList("*.j"));
    blendKitTask.setResources(new FileList("Resources/*"));
    blendKitTask.setLicense(BundleTask.License.LGPL_v2_1);
    blendKitTask.setFlattensSources(true); // FIXME: how do we non flatten?

    if ($CONFIGURATION === "Release")
        blendKitTask.setCompilerFlags("-O2 -Wno-unused-but-set-variable");
    else
        blendKitTask.setCompilerFlags("-DDEBUG -g -Wno-unused-but-set-variable");
});

$BUILD_CJS_PRODUCT_BLENDKIT = path.join($BUILD_CJS_CAPPUCCINO_FRAMEWORKS, "BlendKit");

filedir ($BUILD_CJS_PRODUCT_BLENDKIT, ["BlendKit"], function()
{
    cp_r(blendKitTask.buildProductPath(), $BUILD_CJS_PRODUCT_BLENDKIT);
});

task ("build", ["BlendKit", $BUILD_CJS_PRODUCT_BLENDKIT]);

CLOBBER.include( $BUILD_CJS_PRODUCT_BLENDKIT);
