/*
 * Jakefile
 * AttachedSheet2
 *
 * Created by Saikat Chakrabarti on March 16, 2010.
 * Copyright 2010, gomockingbird.com All rights reserved.
 */

var ENV = require("system").env,
    FILE = require("file"),
    JAKE = require("jake"),
    task = JAKE.task,
    FileList = JAKE.FileList,
    app = require("cappuccino/jake").app,
    configuration = ENV["CONFIG"] || ENV["CONFIGURATION"] || ENV["c"] || "Debug",
    OS = require("os");

app ("AttachedSheet2", function(task)
{
    task.setBuildIntermediatesPath(FILE.join("Build", "AttachedSheet2.build", configuration));
    task.setBuildPath(FILE.join("Build", configuration));

    task.setProductName("AttachedSheet2");
    task.setIdentifier("com.gomockingbird.AttachedSheet2");
    task.setVersion("1.0");
    task.setAuthor("Saikat Chakrabarti and Sheena Pakanati");
    task.setEmail("contact @nospam@ gomockingbird.com");
    task.setSummary("AttachedSheet2");
    task.setSources((new FileList("**/*.j")).exclude(FILE.join("Build", "**")));
    task.setResources(new FileList("Resources/*"));
    task.setIndexFilePath("index.html");
    task.setInfoPlistPath("Info.plist");

    if (configuration === "Debug")
        task.setCompilerFlags("-DDEBUG -g");
    else
        task.setCompilerFlags("-O");
});

function printResults(configuration)
{
    print("----------------------------")
    print(configuration+" app built at path: "+FILE.join("Build", configuration, "AttachedSheet2"));
    print("----------------------------")
}

task ("default", ["AttachedSheet2"], function()
{
    printResults(configuration);
});

task ("build", ["default"]);

task ("debug", function()
{
    ENV["CONFIGURATION"] = "Debug";
    JAKE.subjake(["."], "build", ENV);
});

task ("release", function()
{
    ENV["CONFIGURATION"] = "Release";
    JAKE.subjake(["."], "build", ENV);
});

task ("run", ["debug"], function()
{
    OS.system(["open", FILE.join("Build", "Debug", "AttachedSheet2", "index.html")]);
});

task ("run-release", ["release"], function()
{
    OS.system(["open", FILE.join("Build", "Release", "AttachedSheet2", "index.html")]);
});

task ("deploy", ["release"], function()
{
    FILE.mkdirs(FILE.join("Build", "Deployment", "AttachedSheet2"));
    OS.system(["press", "-f", FILE.join("Build", "Release", "AttachedSheet2"), FILE.join("Build", "Deployment", "AttachedSheet2")]);
    printResults("Deployment")
});

task ("press", ["release"], function()
{
    FILE.mkdirs(FILE.join("Build", "Press", "AttachedSheet2"));
    OS.system(["press", "-f", FILE.join("Build", "Release", "AttachedSheet2"), FILE.join("Build", "Press", "AttachedSheet2")]);
});
 
task ("flatten", ["press"], function()
{
    FILE.mkdirs(FILE.join("Build", "Flatten", "AttachedSheet2"));
    OS.system(["flatten", "-f", "--verbose", "--split", "3", "-c", "closure-compiler", FILE.join("Build", "Press", "AttachedSheet2"), FILE.join("Build", "Flatten", "AttachedSheet2")]);
});
