#!/usr/bin/env narwhal

var FILE = require("file");

require("../../common.jake");

$COMMONJS_PRODUCT               = FILE.join($BUILD_DIR, $CONFIGURATION, "objective-j"),
$COMMONJS_OBJECTIVE_J_PRODUCT   = FILE.join($COMMONJS_PRODUCT, "lib", "Frameworks", "Objective-J");

task ("build", [$COMMONJS_PRODUCT, $COMMONJS_OBJECTIVE_J_PRODUCT]);

filedir ($COMMONJS_PRODUCT, FILE.glob("objective-j/**/*"), function()
{
    rm_rf($COMMONJS_PRODUCT);
    cp_r('objective-j', $COMMONJS_PRODUCT);
});

filedir ($COMMONJS_OBJECTIVE_J_PRODUCT, function()
{
    cp_r(FILE.join($BUILD_DIR, $CONFIGURATION, "Objective-J"), $COMMONJS_OBJECTIVE_J_PRODUCT);
});

//CLOBBER.include($ENVIRONMENT_OBJJ_PRODUCT)
