
require("../../../common.jake");

var path = require("path");

$BLENDTASK              = "blendtask.j";
$BUILD_CJS_BLENDTASK    = path.join($BUILD_CJS_CAPPUCCINO, "lib", "cappuccino", "jake", "blendtask.j");

filedir($BUILD_CJS_BLENDTASK, [$BLENDTASK], function()
{
    cp_r($BLENDTASK, $BUILD_CJS_BLENDTASK);
});

task("build", [$BUILD_CJS_BLENDTASK]);

CLOBBER.include($BUILD_CJS_BLENDTASK);
