#!/bin/bash

# get path of the executable
SELF_PATH=$(cd -P -- "$(dirname -- "$0")" && pwd -P) && SELF_PATH=$SELF_PATH/$(basename -- "$0")

# resolve symlinks
if [ -h $SELF_PATH ]; then
    SELF_PATH=`readlink $SELF_PATH`
fi

SELF_DIR=`dirname $SELF_PATH`
OBJJ_HOME=`dirname $SELF_DIR`
OBJJ_LIB="$OBJJ_HOME/lib"

CLASSPATH_TMP="$OBJJ_LIB:$OBJJ_LIB/js.jar:$OBJJ_HOME/lib/$(basename $SELF_PATH)"

#OBJJ="$OBJJ_LIB/objj.js"
RLWRAP=`which rlwrap`

# if there's a "lib" directory, add all the jars from it
if [ -d "lib" ]; then
    JARS=`find ./lib -name '*.jar' 2> /dev/null | tr "\n" ":"`
    CLASSPATH="$JARS:$CLASSPATH"
fi

# convert paths for Cygwin
if [[ `uname` == CYGWIN* ]]; then
    OBJJ_HOME=`cygpath -wp "$OBJJ_HOME"`
    #OBJJ=`cygpath -wp "$OBJJ"`
    CLASSPATH_TMP=`cygpath -wp "$CLASSPATH_TMP"`
	CLASSPATH="$CLASSPATH_TMP;$CLASSPATH"
else	
	CLASSPATH="$CLASSPATH_TMP:$CLASSPATH"
fi

export OBJJ_HOME

$RLWRAP java -cp $CLASSPATH main $@
#$RLWRAP java -cp $CLASSPATH org.mozilla.javascript.tools.shell.Main $OBJJ $@
