#!/usr/bin/env ruby

require 'rake'
require '../../common'


subprojects = %w{cplutil objj objjc}

%w(build clean clobber).each do |task_name|
  task task_name do
    subrake(subprojects, task_name)
  end
end
