#!/usr/bin/env ruby

require '../../common'
require 'objective-j'
require 'rake'
require 'rake/clean'

$ENVIRONMENT_NARWHAL_PRODUCT = $ENVIRONMENT_DIR
$ENVIRONMENT_OBJJ_PRODUCT = File.join($ENVIRONMENT_NARWHAL_PRODUCT, 'packages', 'objj')

$EXECUTABLES = ['objj', 'objjc', 'cplutil']

task :build do
  rm_rf($ENVIRONMENT_OBJJ_PRODUCT)
  cp_r('objj', $ENVIRONMENT_OBJJ_PRODUCT)
  
  $EXECUTABLES.each do |executable|
    symlink_executable File.join($ENVIRONMENT_BIN_DIR, executable)
  end
end

CLOBBER.include($ENVIRONMENT_OBJJ_PRODUCT)
