/*
 * Jakefile
 * CPBrowserTest
 *
 * Created by Ross Boucher on March 23, 2010.
 * Copyright 2010, Your Company All rights reserved.
 */

var ENV = process.env,
    cp = require("child_process"),
    fs = require("fs"),
    path = require("path"),
    task = JAKE.task,
    FileList = JAKE.FileList,
    app = CAPPUCCINO.Jake.applicationtask.app,
    configuration = ENV["CONFIG"] || ENV["CONFIGURATION"] || ENV["c"] || "Debug";

app ("CPBrowserTest", function(task)
{
    task.setBuildIntermediatesPath(path.join("Build", "CPBrowserTest.build", configuration));
    task.setBuildPath(path.join("Build", configuration));

    task.setProductName("CPBrowserTest");
    task.setIdentifier("com.yourcompany.CPBrowserTest");
    task.setVersion("1.0");
    task.setAuthor("Your Company");
    task.setEmail("feedback @nospam@ yourcompany.com");
    task.setSummary("CPBrowserTest");
    task.setSources((new FileList("**/*.j")).exclude(path.join("Build", "**")));
    task.setResources(new FileList("Resources/*"));
    task.setIndexFilePath("index.html");
    task.setInfoPlistPath("Info.plist");

    if (configuration === "Debug")
        task.setCompilerFlags("-DDEBUG -g");
    else
        task.setCompilerFlags("-O");
});

function printResults(configuration)
{
    console.log("----------------------------");
    console.log(configuration+" app built at path: "+path.join("Build", configuration, "CPBrowserTest"));
    console.log("----------------------------");
}

task ("default", ["CPBrowserTest"], function()
{
    printResults(configuration);
});

task ("build", ["default"]);

task ("debug", function()
{
    ENV["CONFIGURATION"] = "Debug";
    JAKE.subjake(["."], "build", ENV);
});

task ("release", function()
{
    ENV["CONFIGURATION"] = "Release";
    JAKE.subjake(["."], "build", ENV);
});

task ("run", ["debug"], function()
{
    cp.execSync(["open", path.join("Build", "Debug", "CPBrowserTest", "index.html")].join(" "), { stdio: "inherit" });
});

task ("run-release", ["release"], function()
{
    cp.execSync(["open", path.join("Build", "Release", "CPBrowserTest", "index.html")].join(" "), { stdio: "inherit" });
});

task ("deploy", ["release"], function()
{
    fs.mkdirSync(path.join("Build", "Deployment", "CPBrowserTest"), { recursive: true });
    cp.execSync(["press", "-f", path.join("Build", "Release", "CPBrowserTest"), path.join("Build", "Deployment", "CPBrowserTest")].join(" "), { stdio: "inherit" });
    printResults("Deployment")
});
