#!/bin/sh

# if OBJJ_HOME isn't set, try to determine it out
if [ -z $OBJJ_HOME ]; then
    SELF_PATH=$(cd -P -- "$(dirname -- "$0")" && pwd -P) && SELF_PATH=$SELF_PATH/$(basename -- "$0")
    SELF_DIR=`dirname $SELF_PATH`
    
    export OBJJ_HOME="`dirname $SELF_DIR`/share/objj"
    
    if [ -d $OBJJ_HOME ]; then
        echo "OBJJ_HOME not set, defaulting to $OBJJ_HOME" 1>&2
    else
        echo "OBJJ_HOME not set, default at $OBJJ_HOME doesn't exist, exiting" 1>&2 
        exit 2
    fi
fi

OBJJ_LIB="$OBJJ_HOME/lib"
CLASSPATH="$OBJJ_LIB:$OBJJ_LIB/js.jar:$CLASSPATH"

OBJJ="$OBJJ_LIB/objj.js"
RLWRAP=`which rlwrap`
FRAMEWORKS="$STEAM_BUILD"

# if there's a "lib" directory, add all the jars from it
if [ -d "lib" ]; then
    JARS=`find ./lib -name '*.jar' 2> /dev/null | tr "\n" ":"`
    CLASSPATH="$JARS:$CLASSPATH"
fi

# convert paths for Cygwin
UNAME=`uname`
case "$UNAME" in
    CYGWIN*)
        OBJJ_HOME=`cygpath -wp "$OBJJ_HOME"`
        OBJJ_LIB=`cygpath -wp "$OBJJ_LIB"`
        OBJJ=`cygpath -wp "$OBJJ"`
        FRAMEWORKS=`cygpath -w "$FRAMEWORKS"`
        STEAM_BUILD=`cygpath -w "$STEAM_BUILD"`
        CLASSPATH=`cygpath -wp "$CLASSPATH"`
        ;;
    *)
        ;;
esac

#if [ -e $STEAM_BUILD/Objective-J.build/Release/Rhino ]; then
    $RLWRAP java -classpath $CLASSPATH objj $OBJJ_LIB $STEAM_BUILD $@
    #$RLWRAP java -classpath $CLASSPATH org.mozilla.javascript.tools.shell.Main $OBJJ $OBJJ_LIB $STEAM_BUILD $@
#else
#    echo "Missing frameworks at $STEAM_BUILD/Objective-J.build/Release/Rhino" 1>&2
#fi
