/*
 * Jakefile
 * CPTextField
 *
 * Created by Alexander Ljungberg on August 2, 2010.
 * Copyright 2010, WireLoad, LLC All rights reserved.
 */

var ENV = require("system").env,
    FILE = require("file"),
    JAKE = require("jake"),
    task = JAKE.task,
    FileList = JAKE.FileList,
    app = require("cappuccino/jake").app,
    configuration = ENV["CONFIG"] || ENV["CONFIGURATION"] || ENV["c"] || "Debug",
    OS = require("os");

app ("CPTextField", function(task)
{
    task.setBuildIntermediatesPath(FILE.join("Build", "CPTextField.build", configuration));
    task.setBuildPath(FILE.join("Build", configuration));

    task.setProductName("CPTextField");
    task.setIdentifier("com.yourcompany.CPTextField");
    task.setVersion("1.0");
    task.setAuthor("WireLoad, LLC");
    task.setEmail("feedback @nospam@ yourcompany.com");
    task.setSummary("CPTextField");
    task.setSources((new FileList("**/*.j")).exclude(FILE.join("Build", "**")));
    task.setResources(new FileList("Resources/**"));
    task.setIndexFilePath("index.html");
    task.setInfoPlistPath("Info.plist");

    if (configuration === "Debug")
        task.setCompilerFlags("-DDEBUG -g");
    else
        task.setCompilerFlags("-O");
});

task ("default", ["CPTextField"], function()
{
    printResults(configuration);
});

task ("build", ["default"]);

task ("debug", function()
{
    ENV["CONFIGURATION"] = "Debug";
    JAKE.subjake(["."], "build", ENV);
});

task ("release", function()
{
    ENV["CONFIGURATION"] = "Release";
    JAKE.subjake(["."], "build", ENV);
});

task ("run", ["debug"], function()
{
    OS.system(["open", FILE.join("Build", "Debug", "CPTextField", "index.html")]);
});

task ("run-release", ["release"], function()
{
    OS.system(["open", FILE.join("Build", "Release", "CPTextField", "index.html")]);
});

task ("deploy", ["release"], function()
{
    FILE.mkdirs(FILE.join("Build", "Deployment", "CPTextField"));
    OS.system(["press", "-f", FILE.join("Build", "Release", "CPTextField"), FILE.join("Build", "Deployment", "CPTextField")]);
    printResults("Deployment")
});

task ("desktop", ["release"], function()
{
    FILE.mkdirs(FILE.join("Build", "Desktop", "CPTextField"));
    require("cappuccino/nativehost").buildNativeHost(FILE.join("Build", "Release", "CPTextField"), FILE.join("Build", "Desktop", "CPTextField", "CPTextField.app"));
    printResults("Desktop")
});

task ("run-desktop", ["desktop"], function()
{
    OS.system([FILE.join("Build", "Desktop", "CPTextField", "CPTextField.app", "Contents", "MacOS", "NativeHost"), "-i"]);
});

function printResults(configuration)
{
    print("----------------------------");
    print(configuration+" app built at path: "+FILE.join("Build", configuration, "CPTextField"));
    print("----------------------------");
}
