require ("../../common.jake");

var task = require("jake").task;

task ("build", function()
{
    sudo(["mkdir", "-p", "/usr/local/narwhal/bin"])
    sudo(["cp", "capp_lint", "/usr/local/narwhal/bin"]);

    copyManPage("capp_lint", 1);
});

task ("default", ["build"]);