require("../../../common.jake");

const path = require("path");

var callback;

function callbackFunction(blendtask) {
    callback(blendtask);
}

require("../../../CommonJS/lib/cappuccino/jake.js").initilize(callbackFunction);

$BUILD_CJS_BLENDTASK = path.join($BUILD_CJS_CAPPUCCINO, "lib", "cappuccino", "jake", "blendtask.j");

var promise = new Promise((resolve, reject) => {
    callback = function(BLEND_TASK) {
        exports.BlendTask = BLEND_TASK.BlendTask;
        exports.blend = BLEND_TASK.blend;
        defineBlendTask().then(() => {
            resolve();
            delete exports.jakePromise;
        });
    }
});

async function defineBlendTask() {
    await exports.blend ("Aristo2.blend", function(aristoTask)
    {
        aristoTask.setBuildIntermediatesPath(path.join($BUILD_DIR, "Aristo2.build", $CONFIGURATION))
        aristoTask.setBuildPath(path.join($BUILD_DIR, $CONFIGURATION));

        aristoTask.setThemeDescriptors(new FileList("ThemeDescriptors.j"));
        aristoTask.setIdentifier("com.280n.blend.Aristo2");
        aristoTask.setResources(new FileList("Resources/*"));
    });
    task ("build", ["Aristo2.blend"]);    
}

exports.jakePromise = promise;