
require("../common.jake");

// nib2cib uses fontinfo and imagesize and capp uses nib2cib
subtasks(["fontinfo", "imagesize", "nib2cib", "capp", "dump_theme", "NativeHost", "XcodeCapp"], ["build"/*, "clean", "clobber"*/]);

subtasks(["fontinfo", "imagesize"], ["clean", "clobber"]);
