#!/usr/bin/env ruby

require 'rake'
require '../common'

subprojects = %w{Rake capp bake nib2cib press}

%w(build clean clobber).each do |task_name|
  task task_name do
    subrake(subprojects, task_name)
  end
end

#task :deploy => [:build]