#!/usr/bin/env narwhal

require ("../../common.jake");


app ("capp", function(cappTask)
{
    cappTask.setBuildIntermediatesPath(FILE.join($BUILD_DIR, "capp.build", $CONFIGURATION))
    cappTask.setBuildPath($COMMONJS_PRODUCT_LIB);

    cappTask.setAuthor("280 North, Inc.");
    cappTask.setEmail("feedback @nospam@ 280north.com");
    cappTask.setSummary("Setup up Cappuccino projects");
    cappTask.setIdentifier("com.280n.capp");
    cappTask.setLicense(BundleTask.License.LGPL_v2_1);
    cappTask.setVersion("0.7.1");
    cappTask.setSources(new FileList("*.j"));
    cappTask.setResources(new FileList("Resources/*"));
    cappTask.setIncludesNibsAndXibs(true);
    cappTask.setPlatforms([BundleTask.Platform.CommonJS]);
    cappTask.setFlattensSources(true);
    cappTask.setSpritesResources(false);

    if ($CONFIGURATION === "Release")
        cappTask.setCompilerFlags("-O");
    else
        cappTask.setCompilerFlags("-DDEBUG -g");
});

$COMMONJS_CAPP_BIN_PRODUCT = FILE.join($COMMONJS_PRODUCT_BIN, "capp");

// executable in environment directory
filedir($COMMONJS_CAPP_BIN_PRODUCT, ["capp"], function()
{
    make_objj_executable($COMMONJS_CAPP_BIN_PRODUCT);
});

task ("build", ["capp", $COMMONJS_CAPP_BIN_PRODUCT]);

/*
CLOBBER.include($ENVIRONMENT_BIN_PRODUCT, $ENVIRONMENT_LIB_PRODUCT)
*/
