#!/usr/bin/env ruby

require 'rake'
require '../../common'
require 'objective-j'
require 'objective-j/bundletask'


$PRODUCT = :capp
$BUILD_PATH = File.join($BUILD_DIR, $CONFIGURATION, 'capp')
$ENVIRONMENT_BIN_PRODUCT = File.join($ENVIRONMENT_BIN_DIR, 'capp')
$ENVIRONMENT_LIB_PRODUCT = File.join($ENVIRONMENT_LIB_DIR, 'capp')

task :build => [:capp, $ENVIRONMENT_BIN_PRODUCT, $ENVIRONMENT_LIB_PRODUCT]

# Debug Framework
ObjectiveJ::BundleTask.new(:capp) do |t|
    t.name          = 'capp'
    t.identifier    = 'com.280n.capp'
    t.version       = '0.6.5'
    t.author        = '280 North, Inc.'
    t.email         = 'feedback @nospam@ 280north.com'
    t.summary       = 'Setup up Cappuccino projects'
    t.sources       = FileList['*.j']
    t.resources     = FileList['Resources/*']
    t.license       = ObjectiveJ::License::LGPL_v2_1
    t.build_path    = $BUILD_PATH
    t.flag          = 'DEBUG' if $CONFIGURATION == 'Debug'
end

#executable in environment directory
file_d $ENVIRONMENT_BIN_PRODUCT do
    make_objj_executable($ENVIRONMENT_BIN_PRODUCT)
end

file_d $ENVIRONMENT_LIB_PRODUCT => [:capp] do
    cp_r(File.join($BUILD_PATH, '.'), $ENVIRONMENT_LIB_PRODUCT)
end
