
require ("../../common.jake");

var app = require("objective-j/jake").app;
var BundleTask = require("objective-j/jake").BundleTask;

app ("press", function(pressTask)
{
    pressTask.setBuildIntermediatesPath(FILE.join($BUILD_DIR, "press.build", $CONFIGURATION))
    pressTask.setBuildPath($BUILD_CJS_CAPPUCCINO_LIB);

    pressTask.setAuthor("280 North, Inc.");
    pressTask.setEmail("feedback @nospam@ 280north.com");
    pressTask.setSummary("Deployment tool for Cappuccino applications");
    pressTask.setIdentifier("com.280n.press");
    pressTask.setLicense(BundleTask.License.LGPL_v2_1);
    pressTask.setVersion("0.7.9");
    pressTask.setSources(FILE.glob("*.j"));
    pressTask.setResources(FILE.glob("Resources/*"));
    pressTask.setEnvironments(require("objective-j/jake/environment").CommonJS);
    pressTask.setFlattensSources(true);

    if ($CONFIGURATION === "Release")
        pressTask.setCompilerFlags("-O");
    else
        pressTask.setCompilerFlags("-DDEBUG -g");
});

$BUILD_CJS_PRESS = FILE.join($BUILD_CJS_CAPPUCCINO_BIN, 'press');

// executable in environment directory
filedir($BUILD_CJS_PRESS, ["press"], function()
{
    make_objj_executable($BUILD_CJS_PRESS);
});

task ("build", ["press", $BUILD_CJS_PRESS]);

CLOBBER.include($BUILD_CJS_PRESS);
