#!/usr/bin/env ruby

require 'rake'
require '../../common'
require 'objective-j'
require 'objective-j/bundletask'


$PRODUCT = :press
$BUILD_PATH = File.join($BUILD_DIR, $CONFIGURATION, 'press')
$ENVIRONMENT_BIN_PRODUCT = File.join($ENVIRONMENT_BIN_DIR, 'press')
$ENVIRONMENT_LIB_PRODUCT = File.join($ENVIRONMENT_LIB_DIR, 'press')
$ENVIRONMENT_BRIDGE = File.join($ENVIRONMENT_LIB_DIR, 'press', 'bridge.js')

# Debug Framework
ObjectiveJ::BundleTask.new(:press) do |t|
    t.name          = 'press'
    t.identifier    = 'com.280n.press'
    t.version       = '0.6.5'
    t.author        = '280 North, Inc.'
    t.email         = 'feedback @nospam@ 280north.com'
    t.summary       = 'Deployment tool for Cappuccino applications'
    t.sources       = FileList['*.j']
    t.resources     = FileList['Resources/*']
    t.license       = ObjectiveJ::License::LGPL_v2_1
    t.build_path    = $BUILD_PATH
    t.flag          = 'DEBUG' if $CONFIGURATION == 'Debug'
end

#executable in environment directory
file_d $ENVIRONMENT_BIN_PRODUCT do
    make_objj_executable($ENVIRONMENT_BIN_PRODUCT)
end

file_d $ENVIRONMENT_LIB_PRODUCT => [:press] do
    cp_r(File.join($BUILD_PATH, '.'), $ENVIRONMENT_LIB_PRODUCT)
end

file_d $ENVIRONMENT_BRIDGE => [File.join($HOME_DIR, 'Tools', 'Utilities', 'bridge.js')] do
    cp(File.join($HOME_DIR, 'Tools', 'Utilities', 'bridge.js'), $ENVIRONMENT_BRIDGE)
end

task :build => [:press, $ENVIRONMENT_BIN_PRODUCT, $ENVIRONMENT_LIB_PRODUCT, $ENVIRONMENT_BRIDGE]

CLOBBER.include($ENVIRONMENT_BIN_PRODUCT, $ENVIRONMENT_LIB_PRODUCT)
