/*
 * Jakefile
 * UserlandNSTest
 *
 * Created by aparajita on April 11, 2012.
 * Copyright 2012, Victory-Heart Productions All rights reserved.
 */

var ENV = process.env,
    cp = require("child_process"),
    fs = require("fs"),
    path = require("path"),
    task = JAKE.task,
    FileList = JAKE.FileList,
    app = CAPPUCCINO.Jake.applicationtask.app,
    configuration = ENV["CONFIG"] || ENV["CONFIGURATION"] || ENV["c"] || "Debug";

app ("UserlandNSTest", function(task)
{
    task.setBuildIntermediatesPath(path.join("Build", "UserlandNSTest.build", configuration));
    task.setBuildPath(path.join("Build", configuration));

    task.setProductName("UserlandNSTest");
    task.setIdentifier("com.aparajita.UserlandNSTest");
    task.setVersion("1.0");
    task.setAuthor("Victory-Heart Productions");
    task.setEmail("feedback @nospam@ yourcompany.com");
    task.setSummary("UserlandNSTest");
    task.setSources((new FileList("**/*.j")).exclude(path.join("Build", "**")));
    task.setResources(new FileList("Resources/**"));
    task.setIndexFilePath("index.html");
    task.setInfoPlistPath("Info.plist");
    task.setNib2CibFlags("-R Resources/");

    if (configuration === "Debug")
        task.setCompilerFlags("-DDEBUG -g");
    else
        task.setCompilerFlags("-O");
});

task ("default", ["UserlandNSTest"], function()
{
    printResults(configuration);
});

task ("build", ["default"]);

task ("debug", function()
{
    ENV["CONFIGURATION"] = "Debug";
    JAKE.subjake(["."], "build", ENV);
});

task ("release", function()
{
    ENV["CONFIGURATION"] = "Release";
    JAKE.subjake(["."], "build", ENV);
});

task ("run", ["debug"], function()
{
    cp.execSync(["open", path.join("Build", "Debug", "UserlandNSTest", "index.html")].join(" "), { stdio: "inherit" });
});

task ("run-release", ["release"], function()
{
    cp.execSync(["open", path.join("Build", "Release", "UserlandNSTest", "index.html")].join(" "), { stdio: "inherit" });
});

task ("deploy", ["release"], function()
{
    fs.mkdirSync(path.join("Build", "Deployment", "UserlandNSTest"), { recursive: true });
    cp.execSync(["press", "-f", path.join("Build", "Release", "UserlandNSTest"), path.join("Build", "Deployment", "UserlandNSTest")].join(" "), { stdio: "inherit" });
    printResults("Deployment")
});

task ("desktop", ["release"], function()
{
    fs.mkdirSync(path.join("Build", "Desktop", "UserlandNSTest"), { recursive: true });
    require("@objj/nativehost").buildNativeHost(path.join("Build", "Release", "UserlandNSTest"), path.join("Build", "Desktop", "UserlandNSTest", "UserlandNSTest.app"));
    printResults("Desktop")
});

task ("run-desktop", ["desktop"], function()
{
    cp.execSync([path.join("Build", "Desktop", "UserlandNSTest", "UserlandNSTest.app", "Contents", "MacOS", "NativeHost"), "-i"].join(" "), { stdio: "inherit" });
});

function printResults(configuration)
{
    console.log("----------------------------");
    console.log(configuration+" app built at path: "+path.join("Build", configuration, "UserlandNSTest"));
    console.log("----------------------------");
}
