#!/usr/bin/env bash
#
# Cleans up the temporary files generated by the pre-processor.
# The Current Working Directory (CWD) is the main temporary build directory.
#
# ARGUMENTS:
#   $1 - The absolute path to the project root.

# Corrected path to the support script
source "$1/Tools/Documentation/support/processor_setup.sh"

processor_msg "Cleaning up generated header files..."

# The .doc directories are in our CWD (the temp dir), so we can remove them.
if [ -d "AppKit.doc" ]; then
    rm -rf AppKit.doc
fi

if [ -d "Foundation.doc" ]; then
    rm -rf Foundation.doc
fi
