
require ("../../common.jake");

var FILE = require("file"),
    SYSTEM = require("system"),
    path = FILE.Path(FILE.join(SYSTEM.prefix, "bin", "objj2objcskeleton"));

sudo(["cp", "-f", "objj2objcskeleton", path]);
sudo(["chmod", "755", path]);
