
require ("../../common.jake");

var FILE = require("file"),
    SYSTEM = require("system");

const path = require("path");

var p = FILE.Path(path.join(SYSTEM.prefix, "bin", "objj2objcskeleton"));

sudo(["cp", "-f", "objj2objcskeleton", p]);
sudo(["chmod", "755", p]);
